"""Runtime configuration defaults for the bridge server."""

from pathlib import Path

# Packet logging and decode helpers.
LOG_PACKETS = False
LOG_HEX_BYTES = 32
PUBLIC_CHANNELS_FILE = ""
LOCATION_TRACKS_DIR = Path("logs/location_tracks")

# Core bridge listener and status page settings.
CLIENT_TIMEOUT_SECS = 180
STATUS_INTERVAL_SECS = 60
REPLACE_SAME_IP = False
STATUS_BASE_PATH = "/meshbridgestatus"
CLIENT_TX_QUEUE_MAX = 250

# Authentication and remote management settings.
BRIDGE_PASSWORD = ""
ADMIN_PASSWORD = ""
ALLOW_PATH_BLOCK_ADMIN = False

# Firmware update polling.
FIRMWARE_UPDATE_REPO = "MichTronics/MeshCoreNG"
FIRMWARE_UPDATE_CHECK_INTERVAL_SECS = 60 * 60
FIRMWARE_UPDATE_TIMEOUT_SECS = 5

# Transport packet rate limiting.
TRANSPORT_RATE_LIMIT_ENABLE = True
TRANSPORT_RATE_LIMIT_MAX = 20
TRANSPORT_RATE_LIMIT_WINDOW_SECS = 120
TRANSPORT_GLOBAL_RATE_LIMIT_MAX = 80
TRANSPORT_GLOBAL_RATE_LIMIT_WINDOW_SECS = 120

# Bridge dedupe, loop guard, and RF inject controls.
BRIDGE_DEDUPE_ENABLED = True
BRIDGE_DEDUPE_TTL_SECS = 300
BRIDGE_DEDUPE_MAX_ENTRIES = 4096
BRIDGE_LOOPGUARD_ENABLED = True
BRIDGE_LOOPGUARD_WINDOW_SECS = 60
BRIDGE_LOOPGUARD_THRESHOLD = 5
BRIDGE_LOOPGUARD_QUARANTINE_SECS = 120
BRIDGE_RF_INJECT_ENABLED = False
BRIDGE_RF_INJECT_MAX_PER_MIN = 0
BRIDGE_RF_INJECT_MAX_AIRTIME_MS_PER_HOUR = 0
BRIDGE_RF_INJECT_BLOCK_DUTY_ABOVE_PCT = 0.0
BRIDGE_GROUP = "default"
BRIDGE_REQUIRE_GROUP_MATCH = False

# One-byte source ID quarantine settings.
SHORT_ID_QUARANTINE_ENABLED = False
SHORT_ID_QUARANTINE_WINDOW_SECS = 60
SHORT_ID_QUARANTINE_THRESHOLD = 5
SHORT_ID_QUARANTINE_SECS = 900

# Bridge block statistics polling.
BLOCK_STATS_POLL_INTERVAL_SECS = 15
BLOCK_STATS_COMMAND_TIMEOUT_SECS = 4
